### ISSUE TITLE
Customize chunk size in TextPartitioningHandler

### ISSUE THREAD

**Issue by xbotter** [microsoft/semantic-memory#52]
I hope to be able to reduce the size of the chunk to control token consumption during Ask.

**Comment by dluc** [comment]
hi @xbotter for now, the easier path is adding a handler with your custom settings and a custom name. You can choose you handler when sending files, passing a list of "steps".

**Comment by crickman** [comment]
Do this require a lot of re-implementation of code that already exists?  Is this really easier than exposing configuration parameters that for which can be anticipated that users will desire to customzie?

Hard coding these values seems like a transient/place-holder step (as opposed to intentional design) toward just what xbotter has offered.

**Comment by dluc** [comment]
https://github.com/microsoft/semantic-memory/pull/53 merged, thanks!!
